"""initial schema

Creates the full baseline schema from the SQLAlchemy metadata so it stays in
lockstep with the ORM models and is portable across SQLite and PostgreSQL.
Subsequent changes should use autogenerated, incremental migrations.

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-20
"""

from __future__ import annotations

from alembic import op

from app.db import models  # noqa: F401  (register tables on Base.metadata)
from app.db.base import Base

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    Base.metadata.create_all(op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(op.get_bind())
